[package]
name = "katon"
version = "0.1.0"
edition = "2024"

[dependencies]
lalrpop-util = { version = "0.22.2", features = ["lexer"] }
z3 = "0.19.6"

[features]
default = []
static = ["z3/bundled"]

[build-dependencies]
lalrpop = "0.22.2"
