name: Continuous Integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_test:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    env:
      Z3_SYS_Z3_HEADER: >-
        ${{ matrix.os == 'ubuntu-latest' && '/usr/include/z3.h' || 
            (matrix.os == 'macos-latest' && '/opt/homebrew/include/z3.h' || 
            'C:/tools/z3/include/z3.h') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Install Z3 (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y z3 libz3-dev

      - name: Install Z3 (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install z3

      - name: Install Z3 (Windows)
        if: matrix.os == 'windows-latest'
        run: choco install z3

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Run Clippy
        shell: bash
        run: |
          # Set library path hanya untuk macOS dan Windows
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            export Z3_LIBRARY_PATH_OVERRIDE="/opt/homebrew/lib"
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            export Z3_LIBRARY_PATH_OVERRIDE="C:/tools/z3/bin"
          fi
          cargo clippy -- -D warnings

      - name: Run tests
        shell: bash
        run: |
          # Set library path hanya untuk macOS dan Windows
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            export Z3_LIBRARY_PATH_OVERRIDE="/opt/homebrew/lib"
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            export Z3_LIBRARY_PATH_OVERRIDE="C:/tools/z3/bin"
          fi
          cargo test
